language: android
android:
  components:
    - tools
    - platform-tools
    - android-17
    - extra

before_install:
- chmod +x gradlew

licenses:
    - 'android-sdk-preview-license-.+'
    - 'android-sdk-license-.+'
